import logging
from abc import ABC, abstractmethod
from fastapi import HTTPException, status
from langchain_groq import ChatGroq
from app.core.config import settings

# Configure logger for AI / LLM events
logger = logging.getLogger(__name__)


class BaseLLMProvider(ABC):
    """
    Abstract Base Class defining the contract for LLM Providers.
    Any new model provider (e.g., OpenAI, Gemini, Anthropic) must implement
    this interface to ensure provider independence.
    """
    
    @abstractmethod
    def generate_response(self, prompt: str) -> str:
        """
        Submits a prompt message to the underlying model and returns the string response.
        
        Args:
            prompt (str): The prompt message text to be processed.
            
        Returns:
            str: The text content generated by the model.
            
        Raises:
            HTTPException: With corresponding HTTP error code if authentication,
                            network, or upstream service failure occurs.
        """
        pass


class GroqProvider(BaseLLMProvider):
    """
    Concrete implementation of BaseLLMProvider for Groq Cloud API.
    Utilizes LangChain's ChatGroq with the llama-3.1-8b-instant model.
    """
    
    def __init__(self) -> None:
        try:
            # Retrieve and validate Groq API key from settings config
            api_key: str = settings.validate_groq_api_key()
            logger.info("Initializing GroqProvider (llama-3.1-8b-instant)...")
            
            # Initialize the model instance using LangChain Groq wrapper
            self._model = ChatGroq(
                model="llama-3.1-8b-instant",
                api_key=api_key,
                temperature=0.1,  # Deterministic temperature setting
                timeout=30.0      # 30-second timeout limit
            )
            logger.info("GroqProvider initialized successfully.")
        except EnvironmentError as env_err:
            logger.critical(f"GroqProvider initialization failed: missing credentials. Details: {env_err}")
            raise env_err
        except Exception as init_err:
            logger.error(f"Unexpected error during GroqProvider initialization: {init_err}")
            raise init_err

    def generate_response(self, prompt: str) -> str:
        # Validate that the prompt is not empty
        if not prompt or prompt.strip() == "":
            logger.warning("GroqProvider.generate_response called with an empty prompt.")
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Prompt message content cannot be empty."
            )

        logger.info(f"GroqProvider invoking prompt (prompt character length: {len(prompt)})")
        try:
            # Execute invocation call
            response = self._model.invoke(prompt)
            
            # Assert response payload is correct
            if not response or not hasattr(response, 'content'):
                logger.error("GroqProvider model invoke returned empty or invalid response structure.")
                raise HTTPException(
                    status_code=status.HTTP_502_BAD_GATEWAY,
                    detail="Failed to retrieve valid response contents from Groq API."
                )
            
            return str(response.content).strip()

        except HTTPException as http_exc:
            # Re-raise already caught FastAPI HTTPExceptions
            raise http_exc
        except Exception as exc:
            # Log exact error trace locally
            logger.error(f"Error occurred during GroqProvider invocation: {exc}")
            exc_str = str(exc).lower()

            # Map the exception string to appropriate HTTP error codes
            if any(term in exc_str for term in ["auth", "api key", "unauthorized", "invalid key", "401"]):
                raise HTTPException(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    detail="AI service authentication failed. Verify the configured GROQ_API_KEY."
                )
            elif any(term in exc_str for term in ["timeout", "timed out", "deadline", "504"]):
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="Groq LLM service timed out. Please retry shortly."
                )
            elif any(term in exc_str for term in ["conn", "network", "unreachable", "dns", "dnslookup"]):
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="Network error. Unable to establish connection to Groq API servers."
                )
            else:
                # Catch-all API gateway error
                raise HTTPException(
                    status_code=status.HTTP_502_BAD_GATEWAY,
                    detail=f"Bad Gateway. Upstream AI service error: {str(exc)}"
                )


class LLMService:
    """
    High-level Orchestrator Service Layer managing LLM operations.
    Conforms to the Dependency Inversion Principle: depends solely on the
    BaseLLMProvider abstraction, leaving concrete implementation details decoupled.
    """
    
    def __init__(self, provider: BaseLLMProvider) -> None:
        """
        Injects the concrete LLM provider dependency.
        
        Args:
            provider (BaseLLMProvider): An implementation of the BaseLLMProvider interface.
        """
        self._provider = provider
        logger.info(f"LLMService initialized with provider: {provider.__class__.__name__}")

    def generate_response(self, prompt: str) -> str:
        """
        Delegates the prompt execution to the injected provider.
        """
        return self._provider.generate_response(prompt)


# ==============================================================================
# HOW TO ADD A NEW LLM PROVIDER LATER (e.g., OpenAI, Gemini, or Anthropic):
# ==============================================================================
#
# 1. Implement the BaseLLMProvider interface:
#
#    from langchain_openai import ChatOpenAI
#
#    class OpenAIProvider(BaseLLMProvider):
#        def __init__(self) -> None:
#            self._model = ChatOpenAI(
#                model="gpt-4o-mini",
#                api_key=settings.OPENAI_API_KEY,
#                temperature=0.1
#            )
#
#        def generate_response(self, prompt: str) -> str:
#            try:
#                response = self._model.invoke(prompt)
#                return str(response.content).strip()
#            except Exception as e:
#                raise HTTPException(status_code=502, detail=f"OpenAI error: {e}")
#
# 2. Swap the injected provider at instantiation time at the bottom of this file:
#
#    openai_provider = OpenAIProvider()
#    llm_service = LLMService(provider=openai_provider)
# ==============================================================================

# Instantiate dependencies
groq_provider = GroqProvider()

# Inject concrete GroqProvider dependency into the LLMService singleton instance
llm_service = LLMService(provider=groq_provider)
